version: '3.8'

services:
  libraryapi:
    image: postgres
    container_name: libraryapi
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - library-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: seuemail@exemplo.com
      PGADMIN_DEFAULT_PASSWORD: suasenha
    ports:
      - "8080:80"
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
